name        : gparted
version     : 0.24.0
release     : 7
source     :
    - http://sourceforge.net/projects/gparted/files/gparted/gparted-0.24.0/gparted-0.24.0.tar.bz2 : 02398ab33894a59b0bd8707e598c46d8bb56f1413cd54de48eed61e2920ecd60
license     :
    - GPL-2.0
summary     : GParted is a free graphical disk partition editor
builddeps   :
    - pkgconfig(libparted)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(devmapper)
    - pkgconfig(gnome-doc-utils)
description : |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-pkexec.patch
    autoreconf -vfi
    %configure --disable-scrollkeeper \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    install -m 00644 -D $pkgfiles/polkit.policy $installdir/usr/share/polkit-1/actions/com.solus_project.pkexec.gparted.policy
