name       : gparted
version    : 0.33.0
release    : 20
source     :
    - https://github.com/GNOME/gparted/archive/GPARTED_0_33_0.tar.gz : 71df46f9ca71b354027036e51d1f80abdb622402681629b95f749977e8750fae
license    : GPL-2.0-or-later
summary    : GParted is a free graphical disk partition editor
description: |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(devmapper)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(libparted)
    - gnome-common
rundeps    :
    - gpart # Used for data recovery functionality
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-auth_admin_keep-in-policy.patch
    %patch -p1 < $pkgfiles/0002-Don-t-override-icons-at-all-leave-that-to-the-deskto.patch
    %autogen --disable-static \
               --disable-scrollkeeper \
               --disable-doc \
               --enable-xhost-root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
