name       : gparted
version    : 0.33.0
release    : 19
source     :
    - https://netcologne.dl.sourceforge.net/project/gparted/gparted/gparted-0.33.0/gparted-0.33.0.tar.gz : 5023b8c983f88a22e65bf6f09a12ea09369defc008981b52ee8b96a3879f81d6
license    : GPL-2.0-or-later
summary    : GParted is a free graphical disk partition editor
description: |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(devmapper)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(libparted)
rundeps    :
    - gpart # Used for data recovery functionality
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-auth_admin_keep-in-policy.patch
    %patch -p1 < $pkgfiles/0002-Don-t-override-icons-at-all-leave-that-to-the-deskto.patch
    %configure --disable-static \
               --disable-scrollkeeper \
               --disable-doc \
               --enable-xhost-root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
