name       : gparted
version    : 1.4.0
release    : 26
source     :
    - https://gitlab.gnome.org/GNOME/gparted/-/archive/GPARTED_1_4_0/gparted-GPARTED_1_4_0.tar.bz2 : 74010244c1897ab83e3b8ec9dc49e29b860c4a8ee573e3d6b94cc14a5c8b7cae
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GParted is a free graphical disk partition editor
description: |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libparted)
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - gpart # Used for data recovery functionality
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-auth_admin_keep-in-policy.patch
    %patch -p1 < $pkgfiles/0001-Don-t-override-icons-at-all-leave-that-to-the-deskto.patch
    %autogen --disable-static \
               --disable-scrollkeeper \
               --disable-doc \
               --enable-xhost-root
build      : |
    %make
install    : |
    %make_install
