name       : gparted
version    : 0.28.1
release    : 14
source     :
    - http://downloads.sourceforge.net/gparted/gparted-0.28.1.tar.gz : 76891f14394754f7d6ecceba2af0e585bf89f9d780c389a255dcd41a2f45d333
license    :
    - GPL-2.0
summary    : GParted is a free graphical disk partition editor
builddeps  :
    - pkgconfig(libparted)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(devmapper)
    - pkgconfig(gnome-doc-utils)
description: |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-pkexec.patch
    %patch -p1 < $pkgfiles/0002-Don-t-override-icons-at-all-leave-that-to-the-deskto.patch
    autoreconf -vfi
    %configure --disable-scrollkeeper \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    install -m 00644 -D $pkgfiles/polkit.policy $installdir/usr/share/polkit-1/actions/com.solus_project.pkexec.gparted.policy
    install -D -m 00655 $pkgfiles/gparted_wrapper $installdir/usr/sbin/gparted_wrapper
