name       : gparted
version    : 0.31.0
release    : 17
source     :
    - https://netcologne.dl.sourceforge.net/project/gparted/gparted/gparted-0.31.0/gparted-0.31.0.tar.gz : 3b7b49a434d9e4b397bc41a1f5acab8539b9ff402b472dfd83ad77b2decd07ba
license    : GPL-2.0
summary    : GParted is a free graphical disk partition editor
description: |
    GNOME Partition Editor for creating, reorganizing, and deleting disk partitions. It uses libparted from the parted project to detect and manipulate partition tables. Optional file system tools permit managing file systems not included in libparted.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(devmapper)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(libparted)
rundeps    :
    - gpart # Used for data recovery functionality
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-auth_admin_keep-in-policy.patch
    %patch -p1 < $pkgfiles/0002-Don-t-override-icons-at-all-leave-that-to-the-deskto.patch
    %configure --disable-static \
               --disable-scrollkeeper \
               --disable-doc \
               --enable-xhost-root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
